### PR TITLE
Merge latest changes from upstream

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by juliakreger — APPROVED** [review]
/approve

**Comment by juliakreger** [comment]
I do not believe this is required for our current priorities as we realistically need to return to hardware data collection for the next version.

**Comment by elfosardo** [comment]
@juliakreger I agree, just a victim of my PR opening spree

**Comment by juliakreger** [comment]
@elfosardo A "PR opening spree" it has been :)

**Pull request merged**
